#index:
#    path: /
#    controller: App\Controller\DefaultController::index
catch_all:
    path: '{catchall}'
    controller: App\Controller\ErrorController::showError
    requirements:
        catchall: '.*'
